#!/usr/bin/env bash
# Regenerate the source AUR package (undo-cli) for a released tag.
#
# undo-cli-bin is handled by goreleaser's native `aurs:` block, which takes
# the checksums straight from the archives it just built. goreleaser cannot
# do both (aurs + aur_sources panics), so the source package is rendered
# here from the same released tag rather than edited by hand: version and
# checksums drifted apart once already, which fails for every installer.
#
#   packaging/aur/render.sh v0.2.6
set -euo pipefail

tag=${1:?usage: render.sh <tag>}
ver=${tag#v}
repo=edaywalid/undo
base="https://github.com/$repo"
here=$(cd "$(dirname "$0")" && pwd)

fetch() { curl -fsSL --retry 3 --retry-delay 2 "$@"; }

# .SRCINFO is the file the AUR actually reads, so rendering a PKGBUILD
# without regenerating it publishes a package whose metadata disagrees with
# it. That shipped once from a runner with no makepkg, and nothing said so:
# undo-cli sat at 0.2.6 in .SRCINFO while the PKGBUILD moved to 0.2.8.
command -v makepkg >/dev/null ||
    { echo "render.sh: no makepkg, cannot regenerate .SRCINFO" >&2; exit 1; }

# the source tarball is generated by GitHub, so it is not in checksums.txt
echo "hashing the source tarball for $tag"
src=$(fetch "https://codeload.github.com/$repo/tar.gz/refs/tags/$tag" | sha256sum | cut -d' ' -f1)

render() { # render <name> <template>
    mkdir -p "$here/$1"
    sed -e "s|@VER@|$ver|g" -e "s|@SRC@|$src|g" \
        "$here/$2" >"$here/$1/PKGBUILD"
    (cd "$here/$1" && makepkg --printsrcinfo >.SRCINFO)
    echo "wrote $1/PKGBUILD and .SRCINFO"
}

render undo-cli PKGBUILD.src.in

# A PKGBUILD whose pkgver and sums disagree is the exact failure this
# script exists to prevent, so prove they match before anyone ships it.
for d in undo-cli; do
    grep -q "^pkgver=$ver$" "$here/$d/PKGBUILD" ||
        { echo "render.sh: $d pkgver is not $ver" >&2; exit 1; }
    grep -q 'SKIP' "$here/$d/PKGBUILD" &&
        { echo "render.sh: $d still has a SKIP checksum" >&2; exit 1; }
    # the pair is what ships, so check the generated half too
    grep -q "^	pkgver = $ver$" "$here/$d/.SRCINFO" ||
        { echo "render.sh: $d .SRCINFO pkgver is not $ver" >&2; exit 1; }
    grep -q "$src" "$here/$d/.SRCINFO" ||
        { echo "render.sh: $d .SRCINFO source sum missing" >&2; exit 1; }
done
grep -q "$src" "$here/undo-cli/PKGBUILD" ||
    { echo "render.sh: source sum missing" >&2; exit 1; }

echo "undo-cli renders clean at $ver"
